;;; san-help.el --- Help, Documentation & Key Discovery Configuration -*- lexical-binding: t -*-

;;; Commentary:
;; This module optimizes the internal discovery and document navigation stack.
;; It configures:
;; 1. Which-Key: Visual overlay menus that reveal pending key sequences dynamically.
;; 2. Helpful: Comprehensive replacements for standard Emacs help pages, offering
;;    rich contextual text, source code jumps, and execution properties.
;; 3. Telemetry Hooks: Quick navigation bindings to review background system logs.

;;; Code:

;; =============================================================================
;; 1. Interactive Key Discovery (Which-Key Engine)
;; =============================================================================
;; Automatically displays a visual popup list of available keybindings when a 
;; command chain (like C-c or C-x) is left suspended mid-stroke.
;; Note: which-key is built directly into Emacs 29+, requiring no external package download.

(use-package which-key
  :ensure nil                           ; Core built-in component in Emacs 29+
  :init
  (which-key-mode 1))

;; =============================================================================
;; 2. Rich Contextual Documentation Pages (Helpful Stack)
;; =============================================================================
;; Replaces the sparse default text buffers for functions, variables, and keys 
;; with contextual, styled documentation layouts that pull inline source code blocks.

(use-package helpful
  :ensure t
  :bind (("C-h f" . helpful-callable)     ; Replace default function documentation lookup
         ("C-h v" . helpful-variable)     ; Replace default system variable tracking pages
         ("C-h k" . helpful-key)          ; Interactive key stroke combination inspection
         ("C-h x" . helpful-command)      ; Inspect interactive M-x command methods
         ("C-h F" . helpful-function)     ; Strict target documentation for core Lisp functions
         ("C-c C-d" . helpful-at-point))) ; Instantly resolve code properties directly under cursor

;; =============================================================================
;; 3. System Health Diagnostics & Log Inspection
;; =============================================================================

(defun san/view-backup-log ()
  "Instantly open your background system file backup log inside an adjacent window pane.
Targets the encrypted automated logs generated by file system daemons."
  (interactive)
  (let ((log-file (expand-file-name "~/.config/logs/backup.log")))
    (if (file-exists-p log-file)
        (find-file-other-window log-file)
      (user-error "The target backup log file does not exist at path: %s" log-file))))

;; Bind the telemetry diagnostic tool cleanly using modern function quoting
(keymap-global-set "C-c h b" #'san/view-backup-log)

(provide 'san-help)
;;; san-help.el ends here
